### PR TITLE
I just added a new car to the Car class

### PR DESCRIPTION
**Pull request by KseniiaMazanko**
Did I do everything right?

### CODE REVIEW

**Comment by blishchenko1981** [comment]
I cant approve it, did you add me as a reviewer?

**Comment by blishchenko1981** [comment]
never mind, I see it

**Review by blishchenko1981 — APPROVED** [review]

**Comment by Sabirindev** [comment]
cool !

**Review by AbbosB12 — COMMENTED** [review]
Cool code

**Comment by blishchenko1981** [comment]
Kseniia why did u add so many commits instead  of just merge 1 branch, or it is one branch, sorry didnt get it

**Review by blishchenko1981 — APPROVED** [review]

**Review by blishchenko1981 — APPROVED** [review]

**Comment by KseniiaMazanko** [comment]
I got confused at first, forgot to create a new branch, but now I think I figured it out. Thank you for reviewing. Just finished watching the recordings, hope to practice more with you guys!

**Pull request merged**
