### PR TITLE
Tc002user Completed Login functionality

### PR DESCRIPTION
**Pull request by AbbosB12**
added some automation for locating login button and clicking on the button a nd verifying login successful.

### CODE REVIEW

**Comment by blishchenko1981** [comment]
Hi its good!!!

**Review by blishchenko1981 — APPROVED** [review]

**Comment by AbbosB12** [comment]
Thank you for review my code.

**Comment by AbbosB12** [comment]
Can you merge my pull request, please?

**Comment by blishchenko1981** [comment]
Just did

**Pull request merged**
