### PR TITLE
Abb0s tc 200

### PR DESCRIPTION
**Pull request by AbbosB12**
Added automation for login functionality did this did that

### CODE REVIEW

**Comment by AbbosB12** [comment]
Can I merge my code?

**Comment by AbbosB12** [comment]
Can we someone review code :)

**Comment by blishchenko1981** [comment]
great code!!!

**Comment by AbbosB12** [comment]
Thank you for review my code.

**Comment by Sabirindev** [comment]
yes Abbas your codes look fine. please merge it

**Comment by blishchenko1981** [comment]
how we approve it?

**Comment by Sabirindev** [comment]
by reviewing the code

**Pull request merged**
