### PR TITLE
VB100

### PR DESCRIPTION
**Pull request by blishchenko1981**

### CODE REVIEW

**Review by Sabirindev — COMMENTED** [review]
i guess everyone is here

**Review by Sabirindev — COMMENTED** [review]
actually four of us i can see here lol

**Comment by blishchenko1981** [comment]
I dont see Shohzad, and Hende in my list of reviewers. Or Im wrong?

**Review by AbbosB12 — CHANGES_REQUESTED** [review]
Can you added static block here

**Comment by blishchenko1981** [comment]
I try to see it. cant find yet

**Comment by Sabirindev** [comment]
I do not see them neither

**Comment by AbbosB12** [comment]
Me either

**Comment by blishchenko1981** [comment]
Ok I gonna merge it

**Comment by KseniiaMazanko** [comment]
I was able to review the code! I'm with you guys!

**Pull request merged**
