### PR TITLE
commit from Shokhzod

### PR DESCRIPTION
**Pull request by SHOKHZODJURAEV**
how is my code?

### CODE REVIEW

**Comment by blishchenko1981** [comment]
what is in your code

**Review by Marat311 — COMMENTED** [review]
i see main method

**Comment by SHOKHZODJURAEV** [comment]
for while loop

**Comment by AbbosB12** [comment]
I don't read your commit

**Comment by atila-a** [comment]
for practice

**Comment by AbbosB12** [comment]
Great started

**Pull request merged**
